---
# tasks file for Win_Wordpress
- name: Make sure the WordPress site folder is present
  win_dsc5:
    resource_name="file"
    Ensure="Present"
    Type="Directory"
    DestinationPath="C:\WordPress"
  tags:
    - Filesystem

# - name: Remove default web site
#   win_dsc5:
#     resource_name="xWebSite"
#     item_name="Default Web Site"
#     Ensure="Absent"

- name: Make sure the WordPress Iis site is present
  win_dsc5:
    resource_name="xWebSite"
    item_name="WordPress"
    Ensure="Present"
    State="Started"
    DefaultPage="index.php"
    ApplicationPool="DefaultAppPool"
    PhysicalPath="C:\WordPress"
  tags:
    - WordPress

- name: Make sure the WordPress archive is in the package folder
  win_dsc5:
    resource_name="xRemoteFile"
    Uri="http://WordPress.org/latest.zip"
    DestinationPath="C:\packages\wordpress.zip"
  tags:
    - WordPress

- name: Make sure wordpress file is in the root WP Directory
  win_dsc5:
    resource_name="xArchive"
    Path="C:\packages\wordpress.zip"
    Destination="C:\Wordpress"
  tags:
    - WordPress